services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - default
      - taski
    restart_policy:
      condition: on-failure


networks:
  taski:
    external: true
    name: taski-back_default